apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmqcluster-dev
spec:
  replicas: 2
  resources:
    requests:
      cpu: 250m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi
  rabbitmq:
          additionalConfig: |
                  log.console.level = info
                  channel_max = 700
                  default_user= admin 
                  default_pass = admin
                  default_user_tags.administrator = true
  service:
    type: LoadBalancer
